"device" : "cuda"
"seed" : 0

"wandb_project_name": "sas"
"data_dir": "~/SAS/shared_data/"
"data_file": "SAS_data_v1.csv"
"model_dir" : "./models/"
"output_dir" : "./outputs/"

"max_steps" : 7
# "n_epochs" : 3
"n_epochs" : 300
"num_workers" : 6
"max_seq_len" : 10

# "batch_size" : 3
"batch_size" : 100
"dropout" : 0.2
# "hidden_size" : 8
"hidden_size" : 6
"emb_size" : 128
# "n_head" : 2
"n_head" : 2
"train_ratio" : 0.8
"lr" : 0.01

"cate_cols" :
- 'summonerId'
- 'matchId'
- 'position'
- 'teamId'
- 'individualPosition' 
- 'role'
- 'championId'
- 'win'
- 'defense'
- 'flex'
- 'offense'
- 'item0'
- 'item1'
- 'item2'
- 'item3'
- 'item4'
- 'item5'
- 'item6'
- 'summoner1Id'
- 'summoner2Id'


"cont_cols" :
- 'summonerLevel'
- 'champLevel'
- 'summoner1Casts'
- 'summoner2Casts'
- 'kills'
- 'deaths'
- 'assists'
- 'goldEarned'
- 'visionScore'
- 'visionWardsBoughtInGame'
- 'wardsPlaced'
- 'wardsKilled'
- 'totalDamageDealtToChampions'
- 'totalDamageTaken'
- 'timeCCingOthers'
- 'totalTimeCCDealt'
- 'totalHeal'
- 'totalMinionsKilled'
- 'totalAllyJungleMinionsKilled'
- 'dragonKills'
- 'baronKills'
- 'objectivesStolen'
- 'turretKills'
- 'turretsLost'
- 'turretTakedowns'
- 'commandPings'
- 'dangerPings'
- 'holdPings'
- 'needVisionPings'
- 'onMyWayPings'
- 'longestTimeSpentLiving'
- 'spell1Casts'
- 'spell2Casts'
- 'spell3Casts'
- 'spell4Casts'
- 'epicMonsterSteals'
- 'stealthWardsPlaced'
- 'abilityUses'
- 'gameDuration'

'indexing_cols' :
  'other':
    - 'teamId'
    - 'individualPosition'
    - 'role'
    - 'championId'
    - 'win'
    - 'defense'
    - 'flex'
    - 'offense'
  'item' :
    - 'item0'
    - 'item1'
    - 'item2'
    - 'item3'
    - 'item4'
    - 'item5'
    - 'item6'
  'summonerSpell' :
    - 'summoner1Id'
    - 'summoner2Id'
