"device" : "cuda"

"n_epochs" : 300
"batch_size" : 100
"dropout" : 0.4
"hidden_size" : 100
"emb_size" : 256
"n_head" : 2

"cate_cols" :
- 'position'
- 'teamId'
- 'individualPosition' 
- 'role'
- 'championId'
- 'win'
- 'defense'
- 'flex'
- 'offense'
- 'item0'
- 'item1'
- 'item2'
- 'item3'
- 'item4'
- 'item5'
- 'item6'
- 'summoner1Id'
- 'summoner2Id'


"cont_cols" :
- 'summonerLevel'
- 'champLevel'
- 'summoner1Casts'
- 'summoner2Casts'
- 'kills'
- 'deaths'
- 'assists'
- 'goldEarned'
- 'visionScore'
- 'visionWardsBoughtInGame'
- 'wardsPlaced'
- 'wardsKilled'
- 'totalDamageDealtToChampions'
- 'totalDamageTaken'
- 'timeCCingOthers'
- 'totalTimeCCDealt'
- 'totalHeal'
- 'totalMinionsKilled'
- 'totalAllyJungleMinionsKilled'
- 'dragonKills'
- 'baronKills'
- 'objectivesStolen'
- 'turretKills'
- 'turretsLost'
- 'turretTakedowns'
- 'commandPings'
- 'dangerPings'
- 'holdPings'
- 'needVisionPings'
- 'onMyWayPings'
- 'longestTimeSpentLiving'
- 'spell1Casts'
- 'spell2Casts'
- 'spell3Casts'
- 'spell4Casts'
- 'epicMonsterSteals'
- 'stealthWardsPlaced'
- 'abilityUses'
- 'gameDuration'

'indexing_cols' :
  'other':
    - 'teamId'
    - 'individualPosition'
    - 'role'
    - 'championId'
    - 'win'
    - 'defense'
    - 'flex'
    - 'offense'
  'item' :
    - 'item0'
    - 'item1'
    - 'item2'
    - 'item3'
    - 'item4'
    - 'item5'
    - 'item6'
  'summonerSpell' :
    - 'summoner1Id'
    - 'summoner2Id'
