# Generated by Django 5.0.2 on 2024-03-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Champion",
            fields=[
                ("version", models.CharField(max_length=255)),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("key", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("blurb", models.TextField()),
                ("info", models.JSONField()),
                ("image", models.JSONField()),
                ("tags", models.JSONField()),
                ("partype", models.CharField(max_length=255)),
                ("stats", models.JSONField()),
            ],
        ),
    ]
