# Generated by Django 5.0.2 on 2024-03-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_champion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summoner",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
