# Generated by Django 5.0.2 on 2024-03-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_leagueentry"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="leagueentry",
            constraint=models.UniqueConstraint(
                fields=("summoner", "queue_type"), name="unique_league_entry"
            ),
        ),
    ]
