# Generated by Django 5.0.2 on 2024-03-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_summoner_app_summone_name_9a15eb_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="summoner",
            name="account_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="summoner",
            name="profile_icon_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="summoner",
            name="puuid",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="summoner",
            name="revision_date",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="summoner",
            name="summoner_level",
            field=models.IntegerField(null=True),
        ),
    ]
