# Generated by Django 5.0.2 on 2024-03-04 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SummonerInfo",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("account_id", models.CharField(max_length=100)),
                ("profile_icon_id", models.IntegerField()),
                ("revision_date", models.BigIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("puuid", models.CharField(max_length=100)),
                ("summoner_level", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="riot_id",
        ),
        migrations.AddField(
            model_name="appuser",
            name="summoner_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.summonerinfo",
            ),
        ),
    ]
