name: Web CI

on:
  push:
    branches: [ "*" ]
    paths:
      - 'web/project/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Black
      run: black --check web/project

    - name: Run Ruff
      run: ruff check web/project

    - name: Run Mypy
      run: mypy .  
